# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 22:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamefy', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gamer',
        ),
    ]
