# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-09 07:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamefy', '0003_game_gamer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamer',
            name='game_one_score',
            field=models.IntegerField(),
        ),
    ]
