# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-09 07:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamefy', '0004_auto_20171109_1331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamer',
            name='game_one_score',
        ),
    ]
