# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-09 07:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamefy', '0005_remove_gamer_game_one_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamer',
            name='username',
        ),
        migrations.DeleteModel(
            name='Gamer',
        ),
    ]
