# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 11:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamefy', '0009_auto_20171109_1345'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamer',
            old_name='username',
            new_name='player',
        ),
    ]
