# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 11:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamefy', '0010_auto_20171115_1716'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamer',
            old_name='player',
            new_name='user',
        ),
    ]
